name: 2024_04_Gerd_Fornahl_Gedenkturnier_8

on:
  push:
    branches:
      - main
    paths:
      - "2024_04_Gerd_Fornahl_Gedenkturnier_8/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber davfs2

      - name: Build PDFs
        run: |
          cd 2024_04_Gerd_Fornahl_Gedenkturnier_8
          pdflatex 2024_04_Gerd_Fornahl_Gedenkturnier_8.tex
          bibtex 2024_04_Gerd_Fornahl_Gedenkturnier_8.aux
          pdflatex 2024_04_Gerd_Fornahl_Gedenkturnier_8.tex
          pdflatex 2024_04_Gerd_Fornahl_Gedenkturnier_8.tex
          cd ..
          cp 2024_04_Gerd_Fornahl_Gedenkturnier_8/2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf 2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf
          cp 2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2024_04_Gerd_Fornahl_Gedenkturnier_8
          path: 2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf

      - name: Upload zur ISV Cloud
        run: |
          NEXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Upload zur ESKOPP Cloud
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Upload zur ISV Cloud Event
        run: |
          NEXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH_EVENT }}/2024_04_Gerd_Fornahl_Gedenkturnier_8/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Upload zur ESKOPP Cloud Event
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_EVENT }}/2024_04_Gerd_Fornahl_Gedenkturnier_8/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Upload zur ESKOPP Latex
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_PUB }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Git Clean
        run: |
          git clean -fX
