name: 2024_05_Rock_meets_Chess

on:
  push:
    branches:
      - main
    paths:
      - "2024_05_Rock_meets_Chess/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: 2024_05_Rock_meets_Chess
          root_file: 2024_05_Rock_meets_Chess.tex

      - name: Copy FS
        run: |
          cp  2024_05_Rock_meets_Chess/2024_05_Rock_meets_Chess.pdf ISV_2024_05_Rock_meets_Chess.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2024_05_Rock_meets_Chess
          path: ISV_2024_05_Rock_meets_Chess.pdf

      - name: Install WebDAV client
        run: sudo apt-get install -y davfs2

      - name: Upload zur ISV Cloud
        run: |
          NEXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_05_Rock_meets_Chess.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")

          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            exit 1
          fi

      - name: Upload zur ESKOPP Cloud
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_05_Rock_meets_Chess.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")

          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
           else
             exit 1
          fi

      - name: Upload zur ISV Cloud Event
        run: |
          NEXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH_EVENT }}/2024_05_Rock_meets_Chess/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_05_Rock_meets_Chess.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")

          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Upload zur ESKOPP Cloud Event
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_EVENT }}/2024_05_Rock_meets_Chess/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_05_Rock_meets_Chess.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")

          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
           fi

      - name: Upload zur ESKOPP Latex
        run: |
          NEXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_PUB }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2024_05_Rock_meets_Chess.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$NEXTCLOUD_URL")

          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Git Clean
        run: |
          git clean -fX
