name: Test Workflow

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: 2024_04_Gerd_Fornahl_Gedenkturnier_8
          root_file: 2024_04_Gerd_Fornahl_Gedenkturnier_8.tex

      - name: Build PDFs
        run: |
          cp 2024_04_Gerd_Fornahl_Gedenkturnier_8/2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2024_04_Gerd_Fornahl_Gedenkturnier_8
          path: ISV_2024_04_Gerd_Fornahl_Gedenkturnier_8.pdf
          compiler: pdflatex
          args: "--synctex=1 --shell-escape --interaction=nonstopmode"
          extra_packages: bibtex
 

      - name: Git Clean
        run: |
          git clean -fX
